#!/bin/sh
#
# vim-sway-nav - Use the same bindings to move focus between sway windows and
# vim splits. Requires the accompanying vim plugin.

dir="$1"

case "$dir" in
    up) ;;
    right) ;;
    down) ;;
    left) ;;
    *)
        echo "USAGE: $0 up|right|down|left"
        exit 1
esac


if focused_pid="$(swaymsg -t get_tree | jq -e '.. | select(.focused? == true).pid')"; then
    if vim_pid="$(./vim-sway-nav-bin "$focused_pid")"; then
        servername_file="${XDG_RUNTIME_DIR:-/tmp}/vim-sway-nav.$vim_pid.servername"
        read -r program servername <"$servername_file"
        serverarg=--server
        if [ -n "$serverarg" ] && [ -n "$servername" ]; then
            "$program" "$serverarg" "$servername" \
                --remote-expr "VimSwayNav('$dir')" >/dev/null 2>&1 \
                && exit 0
        fi
    fi
fi

swaymsg focus "$dir"
